# Generated by Django 3.2.4 on 2022-11-13 20:19

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20221112_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.upload_to),
        ),
    ]
